version: '3'

services:

  web:
    image: superms2/web:latest
    command: ./code/python manage.py runserver 0.0.0.0:8000
    volumes:
      - '.:/code'
    ports:
      - "8000:8000"
    depends_on:
      - db

  migration:
    image: superms2/web:latest
    command: ./code/python manage.py migrate
    volumes:
      - '.:/code'
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: "nonspot"
      POSTGRES_USER: "nonspot"
      POSTGRES_PASSWORD: "789789789D"
    expose:
      - '5432'