version: '3'

services:
  db:
    image: postgres:9.6-alpine
    environment:
      POSTGRES_DB: "nonspot"
      POSTGRES_USER: "nonspot"
      POSTGRES_PASSWORD: "789789789D"
    expose:
      - '5432'
  web:
    restart: always
    build: .
    command: python manage.py migrate
    volumes:
      - '.:/code'
    ports:
      - "8000:8000"
    depends_on:
      - db